# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is 


# run again.  Do not edit this file unless you know what you are doing. 

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Solitaire(object):
    def __init__(self):  
        self.card_labels = []  # Initialize the card_labels list

    def setupUi(self, Solitaire):
        Solitaire.setObjectName("Solitaire")
        Solitaire.resize(800, 600)
        Solitaire.setMaximumSize(QtCore.QSize(800, 600))
        Solitaire.setAutoFillBackground(False)

        # Set the background color of the central widget to green
        self.centralwidget = QtWidgets.QWidget(Solitaire)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: green;")  # Set green background

        # Create labels and set their properties
        self.label = self.create_label(self.centralwidget, 420, 20)
        self.label_2 = self.create_label(self.centralwidget, 530, 20)
        self.label_3 = self.create_label(self.centralwidget, 310, 20)
        self.label_4 = self.create_label(self.centralwidget, 640, 20)
        self.label_5 = self.create_label(self.centralwidget, 120, 170)
        self.label_6 = self.create_label(self.centralwidget, 230, 170)
        self.label_7 = self.create_label(self.centralwidget, 340, 170)
        self.label_8 = self.create_label(self.centralwidget, 450, 170)
        self.label_9 = self.create_label(self.centralwidget, 560, 170)
        self.label_10 = self.create_label(self.centralwidget, 670, 170)
        self.label_11 = self.create_label(self.centralwidget, 20, 20)
        self.label_12 = self.create_label(self.centralwidget, 10, 170)
        self.label_13 = self.create_label(self.centralwidget, 130, 20)
        self.label_14 = self.create_label(self.centralwidget, 120, 190, r"C:\\Users\\Hp\\Music\\Semester 3rd\\Solataire Game\\PNG-cards-1.3\\2_of_clubs.png")
        self.label_15 = self.create_label(self.centralwidget, 230, 190)
        self.label_16 = self.create_label(self.centralwidget, 230, 210)
        self.label_17 = self.create_label(self.centralwidget, 340, 190)
        self.label_18 = self.create_label(self.centralwidget, 340, 210)
        self.label_19 = self.create_label(self.centralwidget, 340, 230)
        self.label_20 = self.create_label(self.centralwidget, 450, 190)
        self.label_21 = self.create_label(self.centralwidget, 450, 210)
        self.label_22 = self.create_label(self.centralwidget, 450, 230)
        self.label_23 = self.create_label(self.centralwidget, 450, 250)
        self.label_24 = self.create_label(self.centralwidget, 560, 190)
        self.label_25 = self.create_label(self.centralwidget, 560, 210)
        self.label_26 = self.create_label(self.centralwidget, 560, 230)
        self.label_27 = self.create_label(self.centralwidget, 560, 250)
        self.label_28 = self.create_label(self.centralwidget, 670, 190)
        self.label_29 = self.create_label(self.centralwidget, 670, 210)
        self.label_30 = self.create_label(self.centralwidget, 670, 230)
        self.label_31 = self.create_label(self.centralwidget, 670, 250)
        self.label_32 = self.create_label(self.centralwidget, 670, 270)
        self.label_33 = self.create_label(self.centralwidget, 670, 290)

        Solitaire.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Solitaire)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Solitaire.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Solitaire)
        self.statusbar.setObjectName("statusbar")
        Solitaire.setStatusBar(self.statusbar)

        self.retranslateUi(Solitaire)
        QtCore.QMetaObject.connectSlotsByName(Solitaire)

    def create_label(self, parent, x, y, image_path=None):
        label = QtWidgets.QLabel(parent)
        label.setGeometry(QtCore.QRect(x, y, 101, 131))
        label.setText("")
        label.setScaledContents(True)
        label.setStyleSheet("border: 2px solid black;")  # Add black edges
        if image_path:
            pixmap = QtGui.QPixmap(image_path)
            label.setPixmap(pixmap.scaled(label.size(), QtCore.Qt.KeepAspectRatio))

        return label

    def retranslateUi(self, Solitaire):
        _translate = QtCore.QCoreApplication.translate
        Solitaire.setWindowTitle(_translate("Solitaire", "MainWindow"))


    def create_label(self, parent, x, y,image_path=None):
        label = QtWidgets.QLabel(parent)
        label.setGeometry(QtCore.QRect(x, y, 101, 131))
        label.setText("")
        label.setScaledContents(True)
        label.setStyleSheet("border: 2px solid black;")  # Add black edges
        if image_path:
            pixmap = QtGui.QPixmap(image_path)
            label.setPixmap(pixmap.scaled(label.size(), QtCore.Qt.KeepAspectRatio))

        return label

    def retranslateUi(self, Solitaire):
        _translate = QtCore.QCoreApplication.translate
        Solitaire.setWindowTitle(_translate("Solitaire", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Solitaire = QtWidgets.QMainWindow()
    ui = Ui_Solitaire()
    ui.setupUi(Solitaire)
    Solitaire.show()
    sys.exit(app.exec_())
